### ISSUE TITLE
How to generate the required fileds for index if I have no relevent data [HELP]

### ISSUE THREAD

**Issue by sagarkar-unbxd** [ten-blue-links/fxt#47]
I understand the indri index must have some specific fields indexed (like `a, td, table`, etc) But what if my document doesn't have a few of these fields and where to give the extra fields. Please ignore my lack of knowledge. Any help is very much appreciated.
Few pointer questions:
1. Will keeping such fields bank effect my features?
2. Can I provide more fields that are not included? Will it be useless?
@lgrz

**Comment by lgrz** [comment]
1. Whether or not the document(s) have the field makes no difference. They just need to be specified in the Indri index configuration at this time.
2. Currently the fields used are hardcoded in the feature extraction process. Therefore additional fields will not be used. We hope to fix this in a future release.

**Comment by sagarkar-unbxd** [comment]
Can you please elaborate on point 1. I am not sure I get it.
Also, an example of such configuration would be very helpful. The link to the doc is broken.

**Comment by lgrz** [comment]
As long as you have the fields in the Indri index configuration everything will work fine. The required fields are listed on the [quick start](https://github.com/ten-blue-links/fxt/blob/master/doc/quick-start.md) page.

Here is an example Indri index configuration: https://gist.github.com/lgrz/44f9e52bf90b75b04d900faa9305fce9

You can find more details in the Indri documentation for indexing: https://lemur.sourceforge.io/indri/IndriIndexer.html

**Comment by sagarkar-unbxd** [comment]
Much appreciate your help.
So before I index my documents I have to convert them to a format that indri can understand, say TREC-3.

So if my document looks something like this:

``` json
{
"title" : "some fancy title of a product",
"desc" : "description of the product",
"some_urls": ["list of some urls, images, etc"],
"some_other_domain_specific_fields": "a lot of them"
}
```
How should I re-format it before I index it?
An example of such a process if possible would be very helpful.

**Comment by sagarkar-unbxd** [comment]
Also, what is the difference between the `myrun.txt` file and the `labels.txt` file in this line?
`./script/label.awk labels.txt myrun.txt > stage0.run`

Please correct me if I am wrong:
1. labels.txt has 1 query-document training relevance label per line, it includes all the combination I want to train on
2. myrun.txt has the same information but the `score` and `run-identifier`, can you please explain them in context of `<query id> Q0 <docid> 0 <score> <run identifier>` from the quick start document

**Comment by lgrz** [comment]
> Much appreciate your help.
> So before I index my documents I have to convert them to a format that indri can understand, say TREC-3.
> 
> So if my document looks something like this:
> 
> ```json
> {
> "title" : "some fancy title of a product",
> "desc" : "description of the product",
> "some_urls": ["list of some urls, images, etc"],
> "some_other_domain_specific_fields": "a lot of them"
> }
> ```
> 
> How should I re-format it before I index it?
> An example of such a process if possible would be very helpful.

I'd suggest taking a look at the Indri quick start guide:
https://sourceforge.net/p/lemur/wiki/Quick%20Start/

**Comment by lgrz** [comment]
> Also, what is the difference between the `myrun.txt` file and the `labels.txt` file in this line?
> `./script/label.awk labels.txt myrun.txt > stage0.run`
> 
> Please correct me if I am wrong:
> 
>     1. labels.txt has 1 query-document training relevance label per line, it includes all the combination I want to train on
> 
>     2. myrun.txt has the same information but the `score` and `run-identifier`, can you please explain them in context of `<query id> Q0 <docid> 0 <score> <run identifier>` from the quick start document

* `labels.txt` is a QREL file, that has judgments. i.e. `<query-id> 0 <docno> <label>`
* `myrun.txt` is a TREC run file. i.e. `<query-id> Q0 <docno> <rank> <score> <run-identifier>`
